name: AWS EKS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EKS_CLUSTER_NAME: mycluster  # Replace with your EKS cluster name
      DOCKER_IMAGE_NAME: khoa/udacity-cloud-devops-capstone  # Replace with your Docker image name

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Authenticate with DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Deploy to AWS EKS
        run: |
          eksctl create cluster --name ${EKS_CLUSTER_NAME} \
                                --version 1.17 \
                                --nodegroup-name standard-workers \
                                --node-type t2.medium \
                                --nodes 2 \
                                --nodes-min 1 \
                                --nodes-max 2 \
                                --node-ami auto \
                                --region ${AWS_REGION}
          sleep 2m
          aws eks update-kubeconfig --name ${EKS_CLUSTER_NAME}
          kubectl config use-context ${EKS_CLUSTER_NAME}
          kubectl config current-context
          kubectl apply -f deploy-k8s.yml
          kubectl rollout restart deployment/simple-web-app
          sleep 2m
          kubectl get nodes
          kubectl get deployments
          kubectl get pods -o wide
          kubectl get service/simple-web-app

      - name: Verify Deployment
        run: |
          EKS_HOSTNAME=$(kubectl get svc simple-web-app -o jsonpath="{.status.loadBalancer.ingress[*].hostname}")
          curl ${EKS_HOSTNAME}:8080

      - name: Check Rollout
        run: |
          kubectl rollout status deployment/simple-web-app
